[package]
name = "bytestring"
version = "1.0.0"
authors = [
    "Nikolay Kim <fafhrd91@gmail.com>",
    "Rob Ede <robjtede@icloud.com>",
]
description = "An immutable UTF-8 encoded string using Bytes as storage"
keywords = ["string", "bytes", "utf8", "web", "actix"]
categories = ["no-std", "web-programming"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-net.git"
documentation = "https://docs.rs/bytestring/"
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
name = "bytestring"
path = "src/lib.rs"

[dependencies]
bytes = "1"
serde = { version = "1.0", optional = true }

[dev-dependencies]
serde_json = "1.0"
ahash = { version = "0.6", default-features = false }
